apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kr40phpac-go 
  janus-idp.io/tekton: kr40phpac-go
  backstage.io/kubernetes-id: kr40phpac-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kr40phpac-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  