apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kr40phpac-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kr40phpac-go 
  name: kr40phpac-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kr40phpac-go 
